	
origin $00086540
text_character_00:
 dialogue_text("VENOM")   
 dialogue_text("X479 ROBOT")
 dialogue_text("VENOM")
 dialogue_text("HOBGOBLIN")
 dialogue_text("BRUTAL BIKER")
 dialogue_text("J JONAH JAMESON")
 dialogue_text("VENOM")
 dialogue_text("SANDMAN")
 dialogue_text("ESCAPED GORILLA")
 dialogue_text("VENOM")
 dialogue_text("ELECTRO")
 dialogue_text("LIGHTNING CREATURE")
 dialogue_text("VENOM")
 dialogue_text("LIZARD")
 dialogue_text("ALLIGATOR")
 dialogue_text("MUTANT JUMPER")
 dialogue_text("VENOM")
 dialogue_text("DOCTOR OCTOPUS")
 dialogue_text("FORKLIFT")