
origin $00084112
text_dialogue_00:
	dialogue_text("GOOD EVENING, NEW YORK.  MY NAME IS OF NO IMPORTANCE.  ")
    dialogue_text("I AM MERELY A CONCERNED CITIZEN--A CITIZEN WHO HAS LEARNED OF SOMETHING MONSTROUS.  ")
    dialogue_text("THE RENEGADE KNOWN AS SPIDER-MAN IS SEEKING REVENGE UPON YOU.  ")
    dialogue_text("HE HAS HIDDEN A BOMB WHICH WILL EXPLODE IN EXACTLY 24 HOURS, LEVELING THIS CITY, ")
    dialogue_text("UNLESS WE FORCE HIM TO CONFESS ITS LOCATION.  ")
    dialogue_text("I OFFER A $10,000 REWARD FOR HIS APPREHENSION.  ")
    dialogue_text("WE MUST PROTECT OURSELVES...       ")
    dialogue_text("                 ")
    
	
	
  origin $000842DC
text_dialogue_01:
    dialogue_text("CONGRATULATIONS, SPIDER-MAN!  ")
    dialogue_text("YOU HAVE BEATEN SOME OF MY BEST-PAID ASSOCIATES.  ")
    dialogue_text("BUT I THINK YOU WILL FIND THE REST OF YOUR ADVENTURE MORE THAN ")
    dialogue_text("A MATCH FOR YOUR ESTEEMED SELF.  ")
    dialogue_text("WHY DON'T YOU TAKE THE CHALLENGE AND PLAY THIS GAME IN A HARDER LEVEL?  ")
    dialogue_text("I DON'T THINK YOU WILL DO SO WELL, NEXT TIME...")
    dialogue_text("                      ")
    
    
origin $00084422
text_dialogue_02:
    dialogue_text("GOOD EVENING ONCE AGAIN, NEW YORK.  ")
    dialogue_text("I REGRET TO INFORM YOU THAT SPIDER-MAN HAS APPARENTLY GONE MAD, ")
    dialogue_text("DESTROYING AN ABANDONED WAREHOUSE AND LURCHING THROUGH THE SEWERS ")
    dialogue_text("IN AN UNCONTROLLED FASHION.  OUR POLICE, OF COURSE, ARE DOING ")
    dialogue_text("A HEROIC JOB, BUT I AM NOW PREPARED TO INCREASE MY OFFER TO $50,000.  ")
    dialogue_text("INCREASE YOUR VIGILANCE--NOW MORE THAN EVER, WE MUST PROTECT OURSELVES...    ")
    dialogue_text("                        ")
    
    
    
origin $000845BF
text_dialogue_03:
    dialogue_text("GOOD EVENING, SPIDER-MAN--OR SHOULD I SAY 'GOOD MORNING?'  ")
    dialogue_text("YOU'RE NOT WRONG--YOU DID DESTROY MY ABILITY TO BROADCAST CITY-WIDE.  ")
    dialogue_text("BUT THIS IS A PRIVATE TRANSMISSION, ON THE BAND UTILIZED BY YOUR SPIDER-TRACER.  ")
    dialogue_text("I REALIZE THAT YOU WILL THUS BE ABLE TO TRACE THE SOURCE OF THIS TRANSMISSION, ")
    dialogue_text("BUT I DON'T BELIEVE EVEN YOU WILL BE FOOLISH ENOUGH TO DO SO.  ")
    dialogue_text("BECAUSE I HAVE HAD YOUR FRIENDS' WIFE BROUGHT TO ME, AND ANY FURTHER ATTEMPT TO ")
    dialogue_text("STOP ME FROM DETONATING THE BOMB IN YOUR NAME WILL CAUSE HER UNFORTUNATE DEMISE.  ")
    dialogue_text("I HOPE YOU NOW REALIZE WITH WHOM YOU ARE DEALING.")
    dialogue_text("                              ")
    
    
    